on:
  workflow_dispatch:
  push:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: lokesh755/my-action/composite@main
      - run: |
          echo ${{ github.action_repository }}
          echo ${{ github.action_ref }}
